ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/system (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B341410>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B341870>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B341C70>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B33A9F0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B3416B0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B341670>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B35F090>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B35F490>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B35F890>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B3415B0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B3419B0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B341B10>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B33AAD0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B35F750>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B35F350>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B35FC90>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B341AD0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B3417F0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B341350>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B35FBD0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B35F870>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B35FAB0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B341FB0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B341750>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B341A90>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B33ABD0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B35F8D0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B35F430>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B36F0B0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B35F770>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
ERROR:__main__:HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /thm/measurement (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0B35FAD0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',))
